name: Build
on:
  pull_request:
  push:
    branches:
    - master
    - 'releases/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
